force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <label>Active</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Count_No_Of_Contacts__c.field-meta.xml
<CustomField>
    <fullName>Count_No_Of_Contacts__c</fullName>
    <label>Count No Of Contacts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AccountCalculator.cls
public class AccountCalculator {

    @future
    public static void countContacts(List<Id> accIds){

        List<Account> accList = [
            SELECT Id, Active__c, (SELECT Id FROM Contacts)
            FROM Account
            WHERE Id IN :accIds
        ];

        for(Account acc : accList){
            if(acc.Active__c == NULL){
                acc.Active__c = 'Yes';
            }
            acc.Count_No_Of_Contacts__c = acc.Contacts.size();
        }

        if(!accList.isEmpty()){
            update accList;
        }
    }
}