force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <label>Active</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Count_No_Of_Contacts__c.field-meta.xml
<CustomField>
    <fullName>Count_No_Of_Contacts__c</fullName>
    <label>Count No Of Contacts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AccountCalculatorTest.cls
@isTest
public class AccountCalculatorTest {
    @isTest
    private static void countContactsTest(){
        List<Account> accList = new List<Account>();
        for(Integer i=0; i<=250; i++){
            accList.add(new Account(Name = 'test23' + i, Active__c = 'Yes'));
        }
        Test.startTest();
        insert accList;
        
        List<Contact> conList = new List<Contact>();
        List<Id> accIds = new List<Id>();
        
        for(Account acc: accList){
            Contact con = new Contact();
            con.FirstName = 'test';
            con.LastName = 'acc.Name';
            con.AccountId = acc.Id;
            conList.add(con);
            accIds.add(acc.Id);
        }
        insert conList;
        AccountCalculator.countContacts(accIds);
        
        Test.stopTest();
        
        List<Account> accs = [SELECT Id, Count_No_Of_Contacts__c FROM Account];
        
        System.assertEquals(1, accs[0].Count_No_Of_Contacts__c, 'Contacts are not counted succesfully.');
        
        
    }
}